package com.railinc.wembley.legacy.domain.dao;

public interface DaoConstants {
	String Y = "Y";
	String N = "N";
	String SUBRULES_COLUMN_CREATED_TIMESTAMP = "CREATED_TIMESTAMP";
	String SUBRULES_COLUMN_ACTION_ARG = "ACTION_ARG";
	String SUBRULES_COLUMN_ACTION = "ACTION";
	String SUBRULES_COLUMN_CONDITION_ARG = "CONDITION_ARG";
	String SUBRULES_COLUMN_CONDITION = "CONDITION";
	String SUBRULES_COLUMN_RULE_TYPE = "RULE_TYPE";
	String SUBRULES_COLUMN_RULE_SEQ = "RULE_SEQ";
	String SUBRULES_COLUMN_RULE_ID = "RULE_ID";
	String SUBRULES_TABLENAME_WO_SCHEMA = "SUBSCRIPTION_RULES";
	String APPLICATION_TABLE_NAME_WO_SCHEMA = "APPLICATIONS";
	String APPLICATION_COLUMN_APP_ID = "APP_ID";
	String APPLICATION_COLUMN_SUPPORTED_NAMESPACES = "SUPPORTED_NAMESPACES";
	String APPLICATION_COLUMN_CREATED_TIMESTAMP = "CREATED_TIMESTAMP";
	String APPLICATION_COLUMN_DEFAULT_DELIVERY_TIMING = "DEFAULT_DELIVERY_TIMING";
	String APPLICATION_COLUMN_ADMIN_EMAIL = "ADMIN_EMAIL";
	String MAILINGLIST_TABLE_NAME_WO_SCHEMA = "MAILING_LISTS";
	String MLSUBSCRIPTION_TABLE_NAME_WO_SCHEMA = "MAILING_LIST_SUBSCRIPTIONS";
	String MLSUBSCRIPTION_COLUMN_LAST_MODIFIED = "LAST_MODIFIED";
	String MLSUBSCRIPTION_COLUMN_SUBSCRIPTION_UID = "SUBSCRIPTION_UID";
	String MLSUBSCRIPTION_COLUMN_DELIVERY_MECHANISM_ARGUMENT = "DELIVERY_MECHANISM_ARGUMENT";
	String MLSUBSCRIPTION_COLUMN_DELIVERY_MECHANISM = "DELIVERY_MECHANISM";
	String MLSUBSCRIPTION_COLUMN_SUB_CLASS_ARGUMENT = "SUB_CLASS_ARGUMENT";
	String MLSUBSCRIPTION_COLUMN_SUB_CLASS = "SUB_CLASS";
	String MLSUBSCRIPTION_COLUMN_SUB_MODE = "SUB_MODE";
	String MLSUBSCRIPTION_COLUMN_TYPE_ARGUMENT = "TYPE_ARGUMENT";
	String MLSUBSCRIPTION_COLUMN_LIST_TYPE = "LIST_TYPE";
	String NOTIFICATION_COLUMN_CREATED_TIMESTAMP = "CREATED_TIMESTAMP";
	String NOTIFICATION_COLUMN_STATE_TIMESTAMP = "STATE_TIMESTAMP";
	String NOTIFICATION_COLUMN_APP_ID = "APP_ID";
	String NOTIFICATION_COLUMN_NOTIFICATION_UID = "NOTIFICATION_UID";
	String NOTIFICATION_COLUMN_EVENT_UID = "EVENT_UID";
	String NOTIFICATION_COLUMN_RETRY_COUNT = "RETRY_COUNT";
	String NOTIFICATION_COLUMN_DELIVERY_TIMING = "DELIVERY_TIMING";
	String NOTIFICATION_COLUMN_STATE = "STATE";
	String NOTIFICATION_STATUS_OPEN = "OPEN";
	String NOTIFICATION_STATUS_CANCELLED = "CANCELLED";
	
	String NOTIFICATIONS_TABLE_NAME_WO_SCHEMA = "NOTIFICATIONS";
	String EVENTS_TABLE_NAME_WO_SCHEMA = "APPLICATION_EVENTS";
}
